[package]
name = "sleipnir"
version = "0.2.16"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Memory safe font operations for Google Fonts."
repository = "https://github.com/googlefonts/sleipnir"
readme = "README.md"
categories = ["text-processing", "parsing", "graphics"]

[features]

[dependencies]
harfrust = "0.12.0"
kurbo = "0.13.1"
png = "0.18.1"
rayon = "1.12.0"
regex = "1"
roxmltree = "0.21.1"
skrifa = { version = "0.44.0", features = ["traversal"] }
smallvec = "1.15.2"
smol_str = "0.3.6"
thiserror = "2.0.18"
tiny-skia = "0.12.0"

[dev-dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
pretty_assertions="1.4"
criterion = "0.7"
write-fonts = "0.50.0"
regex = "1"

[[bench]]
name = "benchmarks"
harness = false
